"""Tests for cookiefile domain suffix checks."""

from src.core.netscape_cookies import cookiefile_has_domain_suffix


def test_cookiefile_has_domain_suffix(tmp_path):
    cookie_path = tmp_path / "cookies.txt"
    cookie_path.write_text(
        "\n".join(
            [
                "# Netscape HTTP Cookie File",
                "# This file was generated by yt-dlp GUI",
                "",
                "www.instagram.com\tTRUE\t/\tTRUE\t2145916800\tsessionid\tabc123",
            ]
        ),
        encoding="utf-8",
    )

    assert cookiefile_has_domain_suffix(str(cookie_path), "instagram.com")
    assert not cookiefile_has_domain_suffix(str(cookie_path), "redgifs.com")
