"""Tests for Netscape cookies parsing and matching."""

import os
import stat

from src.core.netscape_cookies import (
    write_netscape_cookiefile,
    parse_netscape_cookiefile,
    cookie_domain_matches,
    NetscapeCookie,
)


def test_parse_netscape_cookiefile(tmp_path):
    cookie_path = tmp_path / "cookies.txt"
    cookie_path.write_text(
        "\n".join(
            [
                "# Netscape HTTP Cookie File",
                "# This file was generated by yt-dlp GUI",
                "",
                ".instagram.com\tTRUE\t/\tTRUE\t2145916800\tsessionid\tabc123",
            ]
        ),
        encoding="utf-8",
    )

    cookies = parse_netscape_cookiefile(str(cookie_path))
    assert len(cookies) == 1
    cookie = cookies[0]
    assert isinstance(cookie, NetscapeCookie)
    assert cookie.domain == ".instagram.com"
    assert cookie.name == "sessionid"
    assert cookie.value == "abc123"
    assert cookie.path == "/"
    assert cookie.secure is True
    assert cookie.expires == 2145916800


def test_cookie_domain_matches():
    assert cookie_domain_matches(".instagram.com", "www.instagram.com")
    assert cookie_domain_matches("instagram.com", "instagram.com")
    assert not cookie_domain_matches("example.com", "notexample.com")


def test_write_netscape_cookiefile_hardens_permissions(tmp_path):
    cookie_path = tmp_path / "cookies.txt"

    write_netscape_cookiefile(
        str(cookie_path),
        [
            {
                "domain": ".instagram.com",
                "path": "/",
                "secure": True,
                "expires": 2145916800,
                "name": "sessionid",
                "value": "abc123",
            }
        ],
    )

    assert cookie_path.exists()

    if os.name == "posix":
        mode = stat.S_IMODE(cookie_path.stat().st_mode)
        assert mode == 0o600
