"""Utilities to write cookies.txt in Netscape format."""

from __future__ import annotations

import os
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, List


def cookies_to_netscape_lines(cookies: List[Dict]) -> List[str]:
    """
    Convert Playwright cookies to Netscape cookie file lines.

    Args:
        cookies: List of Playwright cookie dicts.

    Returns:
        List of string lines in Netscape format.
    """
    lines: List[str] = [
        "# Netscape HTTP Cookie File",
        "# This file was generated by yt-dlp GUI",
        "",
    ]

    for cookie in cookies:
        domain = cookie.get("domain", "")
        if not domain:
            continue

        include_subdomains = "TRUE" if domain.startswith(".") else "FALSE"
        path = cookie.get("path", "/") or "/"
        secure = "TRUE" if cookie.get("secure") else "FALSE"
        expires = int(cookie.get("expires") or 0)
        name = cookie.get("name", "")
        value = cookie.get("value", "")

        lines.append(
            "\t".join(
                [
                    domain,
                    include_subdomains,
                    path,
                    secure,
                    str(expires),
                    name,
                    value,
                ]
            )
        )

    return lines


def write_netscape_cookiefile(path: str, cookies: List[Dict]) -> None:
    """
    Write a Netscape cookies.txt file to disk.

    Args:
        path: Output file path.
        cookies: List of Playwright cookie dicts.
    """
    output_path = Path(path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    lines = cookies_to_netscape_lines(cookies)
    temp_path = output_path.with_suffix(output_path.suffix + ".tmp")

    temp_path.write_text("\n".join(lines), encoding="utf-8")
    _harden_cookiefile_permissions(temp_path)
    temp_path.replace(output_path)
    _harden_cookiefile_permissions(output_path)


def _harden_cookiefile_permissions(path: Path) -> None:
    """Restrict cookie file access where the platform supports POSIX modes."""
    if os.name != "posix":
        return

    try:
        path.chmod(0o600)
    except OSError:
        pass


@dataclass(frozen=True)
class NetscapeCookie:
    """Parsed Netscape cookie entry."""

    domain: str
    name: str
    value: str
    path: str
    secure: bool
    expires: int


def parse_netscape_cookiefile(path: str) -> List[NetscapeCookie]:
    """
    Parse a Netscape cookies.txt file into cookie entries.

    Args:
        path: Cookies file path.

    Returns:
        List of NetscapeCookie entries.
    """
    cookie_path = Path(path)
    if not cookie_path.exists() or not cookie_path.is_file():
        return []

    cookies: List[NetscapeCookie] = []
    for line in cookie_path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue

        parts = stripped.split("\t")
        if len(parts) != 7:
            continue

        domain, _include_subdomains, path_value, secure, expires, name, value = parts
        try:
            expires_value = int(expires or 0)
        except ValueError:
            expires_value = 0

        cookies.append(
            NetscapeCookie(
                domain=domain,
                name=name,
                value=value,
                path=path_value or "/",
                secure=secure.upper() == "TRUE",
                expires=expires_value,
            )
        )

    return cookies


def cookie_domain_matches(cookie_domain: str, host: str) -> bool:
    """
    Check if a cookie domain applies to a host.

    Args:
        cookie_domain: Domain stored in cookie (may be prefixed with '.')
        host: Hostname to match against
    """
    cookie_value = cookie_domain.lstrip(".").lower()
    host_value = host.strip(".").lower()
    if not cookie_value or not host_value:
        return False
    if host_value == cookie_value:
        return True
    return host_value.endswith(f".{cookie_value}")


def get_cookie_domains(path: str) -> set[str]:
    """
    Return all unique cookie domains from a Netscape cookie file.

    Domains are normalized: stripped of leading dots and lowercased.

    Args:
        path: Cookies file path.

    Returns:
        Set of normalized domain strings.
    """
    return {
        cookie.domain.lstrip(".").lower()
        for cookie in parse_netscape_cookiefile(path)
        if cookie.domain
    }


def domain_suffix_matches_cookie_domains(
    domain_suffix: str, cookie_domains: set[str]
) -> bool:
    """
    Check whether any cookie domain in the set matches a domain suffix.

    Args:
        domain_suffix: Domain suffix to check (e.g., instagram.com).
        cookie_domains: Pre-parsed set of normalized cookie domains.

    Returns:
        True if any cookie domain matches the suffix.
    """
    suffix = domain_suffix.lstrip(".").lower()
    if not suffix:
        return False

    for cookie_domain in cookie_domains:
        if (
            cookie_domain == suffix
            or cookie_domain.endswith(f".{suffix}")
            or suffix.endswith(f".{cookie_domain}")
        ):
            return True

    return False


def cookiefile_has_domain_suffix(path: str, domain_suffix: str) -> bool:
    """
    Check whether a cookie file contains cookies for a domain suffix.

    Args:
        path: Cookies file path.
        domain_suffix: Domain suffix to check (e.g., instagram.com).
    """
    suffix = domain_suffix.lstrip(".").lower()
    if not suffix:
        return False

    for cookie in parse_netscape_cookiefile(path):
        cookie_domain = cookie.domain.lstrip(".").lower()
        if (
            cookie_domain == suffix
            or cookie_domain.endswith(f".{suffix}")
            or suffix.endswith(f".{cookie_domain}")
        ):
            return True

    return False
